# Basic Python

## 1. Split this string

In [9]:
s = "Hi there Esohin!"

In [10]:
s.split()

['Hi', 'there', 'Esohin!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [14]:
a="The diameter of {planet} is {diameter} kilometers"
print(a.format(planet="Earth",diameter = 12742))


The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [24]:
import numpy as np

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4.1 Create an array of 10 zeros? 


## 4.2 Create an array of 10 fives?

In [26]:
import numpy as np
b=np.zeros(10)*0
print(b)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
b=np.ones(10)*5
print(b)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [30]:
S=np.arange(20,35,2)
S

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
C=np.arange(0,9).reshape(3,3)
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [32]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [40]:
import pandas as pd
data=[{'a':12,"b':45},{'a':54,'b':23},{'a':94,'b':76}]
df=pd.DataFrame(data)
print(df)   

SyntaxError: EOL while scanning string literal (3259113285.py, line 2)

SyntaxError: EOL while scanning string literal (2583956652.py, line 1)

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [42]:
a=pd.date_range(start='1/1/2023' ,end='10/2/2023')
print(a)

AttributeError: 'dict' object has no attribute 'date_range'

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [44]:
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lst)
print(dt)


AttributeError: 'dict' object has no attribute 'DataFrame'